spring.application.name=ms-agenda
# Cambiamos el puerto para evitar conflictos (8082)
server.port=8082 

# --- Conexion Oracle Cloud ---
# Se mantiene igual para compartir la instancia de base de datos
spring.datasource.url=jdbc:oracle:thin:@nexushealthdb_low?TNS_ADMIN=${RUTA_WALLET}
spring.datasource.username=user_Alan
spring.datasource.password=Nexus.Alan_1412
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.hikari.maximum-pool-size=2
# --- JPA / Hibernate ---
spring.jpa.show-sql=true
# Formato legible para la defensa tecnica
spring.jpa.properties.hibernate.format_sql=true

# ddl-auto=validate garantiza que las tablas existan antes de arrancar [cite: 360, 362]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect